import type { Match } from "../types";

// Matches estruturado com base nos grupos oficiais
// Cada grupo tem 6 matches (3 rodadas × 2 matches simultâneos por rodada, na maioria)
// A Copa 2026 ocorre de 14 de junho a 13 de julho

const MATCHES_DATA: Omit<Match, "id">[] = [
  // ========== GRUPO A ==========
  // Rodada 1
  {
    home_team: "México",
    away_team: "Coreia do Sul",
    group_name: "A",
    phase: "group_stage",
    stadium: "NRG Stadium",
    city: "Houston",
    match_datetime: "2026-06-14T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "República Tcheca",
    away_team: "África do Sul",
    group_name: "A",
    phase: "group_stage",
    stadium: "AT&T Stadium",
    city: "Dallas",
    match_datetime: "2026-06-14T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Coreia do Sul",
    away_team: "República Tcheca",
    group_name: "A",
    phase: "group_stage",
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    match_datetime: "2026-06-19T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "África do Sul",
    away_team: "México",
    group_name: "A",
    phase: "group_stage",
    stadium: "Allegiant Stadium",
    city: "Las Vegas",
    match_datetime: "2026-06-19T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Coreia do Sul",
    away_team: "África do Sul",
    group_name: "A",
    phase: "group_stage",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    match_datetime: "2026-06-24T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "México",
    away_team: "República Tcheca",
    group_name: "A",
    phase: "group_stage",
    stadium: "MetLife Stadium",
    city: "East Rutherford",
    match_datetime: "2026-06-24T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO B ==========
  // Rodada 1
  {
    home_team: "Canadá",
    away_team: "Qatar",
    group_name: "B",
    phase: "group_stage",
    stadium: "Levi's Stadium",
    city: "Santa Clara",
    match_datetime: "2026-06-15T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Suíça",
    away_team: "Bósnia e Herzegovina",
    group_name: "B",
    phase: "group_stage",
    stadium: "Lincoln Financial Field",
    city: "Philadelphia",
    match_datetime: "2026-06-15T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Bósnia e Herzegovina",
    away_team: "Canadá",
    group_name: "B",
    phase: "group_stage",
    stadium: "Soldier Field",
    city: "Chicago",
    match_datetime: "2026-06-20T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Qatar",
    away_team: "Suíça",
    group_name: "B",
    phase: "group_stage",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    match_datetime: "2026-06-20T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Bósnia e Herzegovina",
    away_team: "Qatar",
    group_name: "B",
    phase: "group_stage",
    stadium: "Empower Field",
    city: "Denver",
    match_datetime: "2026-06-25T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Canadá",
    away_team: "Suíça",
    group_name: "B",
    phase: "group_stage",
    stadium: "Vancouver Stadium",
    city: "Vancouver",
    match_datetime: "2026-06-25T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO C ==========
  // Rodada 1
  {
    home_team: "Brasil",
    away_team: "Escócia",
    group_name: "C",
    phase: "group_stage",
    stadium: "Mercedes-Benz Stadium",
    city: "Atlanta",
    match_datetime: "2026-06-15T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Haiti",
    away_team: "Marrocos",
    group_name: "C",
    phase: "group_stage",
    stadium: "Hard Rock Stadium",
    city: "Miami",
    match_datetime: "2026-06-15T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Marrocos",
    away_team: "Brasil",
    group_name: "C",
    phase: "group_stage",
    stadium: "Neyland Stadium",
    city: "Knoxville",
    match_datetime: "2026-06-20T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Escócia",
    away_team: "Haiti",
    group_name: "C",
    phase: "group_stage",
    stadium: "Bank of America Stadium",
    city: "Charlotte",
    match_datetime: "2026-06-20T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Marrocos",
    away_team: "Haiti",
    group_name: "C",
    phase: "group_stage",
    stadium: "Heinz Field",
    city: "Pittsburgh",
    match_datetime: "2026-06-25T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Escócia",
    away_team: "Brasil",
    group_name: "C",
    phase: "group_stage",
    stadium: "Nissan Stadium",
    city: "Nashville",
    match_datetime: "2026-06-25T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO D ==========
  // Rodada 1
  {
    home_team: "Estados Unidos",
    away_team: "Paraguai",
    group_name: "D",
    phase: "group_stage",
    stadium: "Fulton County Stadium",
    city: "Atlanta",
    match_datetime: "2026-06-16T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Austrália",
    away_team: "Turquia",
    group_name: "D",
    phase: "group_stage",
    stadium: "Acrisure Stadium",
    city: "Pittsburgh",
    match_datetime: "2026-06-16T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Turquia",
    away_team: "Estados Unidos",
    group_name: "D",
    phase: "group_stage",
    stadium: "Q2 Stadium",
    city: "Austin",
    match_datetime: "2026-06-21T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Paraguai",
    away_team: "Austrália",
    group_name: "D",
    phase: "group_stage",
    stadium: "INVESCO Field",
    city: "Denver",
    match_datetime: "2026-06-21T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Turquia",
    away_team: "Paraguai",
    group_name: "D",
    phase: "group_stage",
    stadium: "Folsom Field",
    city: "Boulder",
    match_datetime: "2026-06-26T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Austrália",
    away_team: "Estados Unidos",
    group_name: "D",
    phase: "group_stage",
    stadium: "EverBank Stadium",
    city: "Jacksonville",
    match_datetime: "2026-06-26T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO E ==========
  // Rodada 1
  {
    home_team: "Alemanha",
    away_team: "Costa do Marfim",
    group_name: "E",
    phase: "group_stage",
    stadium: "Caesars Superdome",
    city: "New Orleans",
    match_datetime: "2026-06-16T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Equador",
    away_team: "Curaçao",
    group_name: "E",
    phase: "group_stage",
    stadium: "Providence Park",
    city: "Portland",
    match_datetime: "2026-06-16T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Curaçao",
    away_team: "Alemanha",
    group_name: "E",
    phase: "group_stage",
    stadium: "CenturyLink Field",
    city: "Seattle",
    match_datetime: "2026-06-21T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Costa do Marfim",
    away_team: "Equador",
    group_name: "E",
    phase: "group_stage",
    stadium: "Rio Tinto Stadium",
    city: "Sandy",
    match_datetime: "2026-06-21T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Curaçao",
    away_team: "Costa do Marfim",
    group_name: "E",
    phase: "group_stage",
    stadium: "Snapdragon Stadium",
    city: "San Diego",
    match_datetime: "2026-06-26T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Equador",
    away_team: "Alemanha",
    group_name: "E",
    phase: "group_stage",
    stadium: "Cretin Stadium",
    city: "Minneapolis",
    match_datetime: "2026-06-26T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO F ==========
  // Rodada 1
  {
    home_team: "Holanda",
    away_team: "Suécia",
    group_name: "F",
    phase: "group_stage",
    stadium: "Orlando City Stadium",
    city: "Orlando",
    match_datetime: "2026-06-17T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Tunísia",
    away_team: "Japão",
    group_name: "F",
    phase: "group_stage",
    stadium: "Minute Maid Park",
    city: "Houston",
    match_datetime: "2026-06-17T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Japão",
    away_team: "Holanda",
    group_name: "F",
    phase: "group_stage",
    stadium: "Toyota Stadium",
    city: "Frisco",
    match_datetime: "2026-06-22T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Suécia",
    away_team: "Tunísia",
    group_name: "F",
    phase: "group_stage",
    stadium: "University of Phoenix Stadium",
    city: "Glendale",
    match_datetime: "2026-06-22T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Japão",
    away_team: "Suécia",
    group_name: "F",
    phase: "group_stage",
    stadium: "Midland County Airpark",
    city: "Midland",
    match_datetime: "2026-06-27T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Tunísia",
    away_team: "Holanda",
    group_name: "F",
    phase: "group_stage",
    stadium: "Spartan Stadium",
    city: "East Lansing",
    match_datetime: "2026-06-27T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO G ==========
  // Rodada 1
  {
    home_team: "Bélgica",
    away_team: "Nova Zelândia",
    group_name: "G",
    phase: "group_stage",
    stadium: "Lambeau Field",
    city: "Green Bay",
    match_datetime: "2026-06-17T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Irã",
    away_team: "Egito",
    group_name: "G",
    phase: "group_stage",
    stadium: "Cotton Bowl Stadium",
    city: "Dallas",
    match_datetime: "2026-06-17T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Egito",
    away_team: "Bélgica",
    group_name: "G",
    phase: "group_stage",
    stadium: "Tropicana Field",
    city: "St. Petersburg",
    match_datetime: "2026-06-22T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Nova Zelândia",
    away_team: "Irã",
    group_name: "G",
    phase: "group_stage",
    stadium: "Wrigley Field",
    city: "Chicago",
    match_datetime: "2026-06-22T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Egito",
    away_team: "Nova Zelândia",
    group_name: "G",
    phase: "group_stage",
    stadium: "Fenway Park",
    city: "Boston",
    match_datetime: "2026-06-27T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Irã",
    away_team: "Bélgica",
    group_name: "G",
    phase: "group_stage",
    stadium: "Yankee Stadium",
    city: "New York",
    match_datetime: "2026-06-27T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO H ==========
  // Rodada 1
  {
    home_team: "Espanha",
    away_team: "Cabo Verde",
    group_name: "H",
    phase: "group_stage",
    stadium: "Kauffman Stadium",
    city: "Kansas City",
    match_datetime: "2026-06-18T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Arábia Saudita",
    away_team: "Uruguai",
    group_name: "H",
    phase: "group_stage",
    stadium: "Telus Spark",
    city: "Calgary",
    match_datetime: "2026-06-18T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Uruguai",
    away_team: "Espanha",
    group_name: "H",
    phase: "group_stage",
    stadium: "Commonwealth Stadium",
    city: "Edmonton",
    match_datetime: "2026-06-23T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Cabo Verde",
    away_team: "Arábia Saudita",
    group_name: "H",
    phase: "group_stage",
    stadium: "BC Place",
    city: "Vancouver",
    match_datetime: "2026-06-23T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Uruguai",
    away_team: "Cabo Verde",
    group_name: "H",
    phase: "group_stage",
    stadium: "Mosaic Stadium",
    city: "Regina",
    match_datetime: "2026-06-28T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Arábia Saudita",
    away_team: "Espanha",
    group_name: "H",
    phase: "group_stage",
    stadium: "Sunlife Stadium",
    city: "Montreal",
    match_datetime: "2026-06-28T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO I ==========
  // Rodada 1
  {
    home_team: "França",
    away_team: "Noruega",
    group_name: "I",
    phase: "group_stage",
    stadium: "Dignity Health Sports Park",
    city: "Carson",
    match_datetime: "2026-06-18T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Iraque",
    away_team: "Senegal",
    group_name: "I",
    phase: "group_stage",
    stadium: "Rose Bowl",
    city: "Pasadena",
    match_datetime: "2026-06-18T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Senegal",
    away_team: "França",
    group_name: "I",
    phase: "group_stage",
    stadium: "San Diego Stadium",
    city: "San Diego",
    match_datetime: "2026-06-23T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Noruega",
    away_team: "Iraque",
    group_name: "I",
    phase: "group_stage",
    stadium: "LAFC Stadium",
    city: "Los Angeles",
    match_datetime: "2026-06-23T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Senegal",
    away_team: "Noruega",
    group_name: "I",
    phase: "group_stage",
    stadium: "Dignity Health Park",
    city: "Phoenix",
    match_datetime: "2026-06-28T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Iraque",
    away_team: "França",
    group_name: "I",
    phase: "group_stage",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    match_datetime: "2026-06-28T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO J ==========
  // Rodada 1
  {
    home_team: "Argentina",
    away_team: "Áustria",
    group_name: "J",
    phase: "group_stage",
    stadium: "Mercedes-Benz Superdome",
    city: "New Orleans",
    match_datetime: "2026-06-19T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Argélia",
    away_team: "Jordânia",
    group_name: "J",
    phase: "group_stage",
    stadium: "Soldier Field",
    city: "Chicago",
    match_datetime: "2026-06-19T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Jordânia",
    away_team: "Argentina",
    group_name: "J",
    phase: "group_stage",
    stadium: "Gillette Stadium",
    city: "Foxborough",
    match_datetime: "2026-06-24T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Áustria",
    away_team: "Argélia",
    group_name: "J",
    phase: "group_stage",
    stadium: "FedEx Forum",
    city: "Memphis",
    match_datetime: "2026-06-24T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Jordânia",
    away_team: "Áustria",
    group_name: "J",
    phase: "group_stage",
    stadium: "Guaranteed Rate Field",
    city: "Chicago",
    match_datetime: "2026-06-29T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Argélia",
    away_team: "Argentina",
    group_name: "J",
    phase: "group_stage",
    stadium: "Comerica Park",
    city: "Detroit",
    match_datetime: "2026-06-29T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO K ==========
  // Rodada 1
  {
    home_team: "Portugal",
    away_team: "Congo",
    group_name: "K",
    phase: "group_stage",
    stadium: "SoFi Stadium",
    city: "Los Angeles",
    match_datetime: "2026-06-19T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Uzbequistão",
    away_team: "Colômbia",
    group_name: "K",
    phase: "group_stage",
    stadium: "Viejas Arena",
    city: "San Diego",
    match_datetime: "2026-06-19T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Colômbia",
    away_team: "Portugal",
    group_name: "K",
    phase: "group_stage",
    stadium: "Banc of California Stadium",
    city: "Los Angeles",
    match_datetime: "2026-06-24T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Congo",
    away_team: "Uzbequistão",
    group_name: "K",
    phase: "group_stage",
    stadium: "Dignity Health Park",
    city: "Tempe",
    match_datetime: "2026-06-24T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Colômbia",
    away_team: "Congo",
    group_name: "K",
    phase: "group_stage",
    stadium: "Gila River Stadium",
    city: "Glendale",
    match_datetime: "2026-06-29T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Uzbequistão",
    away_team: "Portugal",
    group_name: "K",
    phase: "group_stage",
    stadium: "Honda Center",
    city: "Anaheim",
    match_datetime: "2026-06-29T20:00:00Z",
    status: "pending",
    result_updated: false,
  },

  // ========== GRUPO L ==========
  // Rodada 1
  {
    home_team: "Inglaterra",
    away_team: "Panamá",
    group_name: "L",
    phase: "group_stage",
    stadium: "Arrowhead Stadium",
    city: "Kansas City",
    match_datetime: "2026-06-20T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Gana",
    away_team: "Croácia",
    group_name: "L",
    phase: "group_stage",
    stadium: "Empower Field",
    city: "Denver",
    match_datetime: "2026-06-20T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 2
  {
    home_team: "Croácia",
    away_team: "Inglaterra",
    group_name: "L",
    phase: "group_stage",
    stadium: "CenturyLink Field",
    city: "Seattle",
    match_datetime: "2026-06-25T16:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Panamá",
    away_team: "Gana",
    group_name: "L",
    phase: "group_stage",
    stadium: "Raymond James Stadium",
    city: "Tampa",
    match_datetime: "2026-06-25T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  // Rodada 3
  {
    home_team: "Croácia",
    away_team: "Panamá",
    group_name: "L",
    phase: "group_stage",
    stadium: "Caesars Superdome",
    city: "New Orleans",
    match_datetime: "2026-06-30T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
  {
    home_team: "Gana",
    away_team: "Inglaterra",
    group_name: "L",
    phase: "group_stage",
    stadium: "Darrell K Royal Stadium",
    city: "Austin",
    match_datetime: "2026-06-30T20:00:00Z",
    status: "pending",
    result_updated: false,
  },
];

// Gerar IDs únicos para cada match
export const MATCHES = MATCHES_DATA.map((match, index) => ({
  ...match,
  id: `match-${index + 1}`,
}));

export const TOTAL_GROUP_STAGE_MATCHES = MATCHES.length;
